import type { Animal, Resource, Report } from "@/types/zoo-types"

export function generateMockData() {
  // Generate mock animals
  const animals: Animal[] = [
    {
      id: "a1",
      name: "Leo",
      species: "Lion",
      gender: "Male",
      age: 8,
      health_status: "Healthy",
      location: "Big Cats Exhibit",
      diet_requirements: "Carnivore diet: 10kg of meat daily",
      medical_history: [
        {
          date: "2023-10-15",
          type: "Routine Checkup",
          notes: "All vitals normal, good condition",
          treatment: "None required",
        },
        {
          date: "2023-07-22",
          type: "Vaccination",
          notes: "Annual vaccination administered",
          treatment: "Standard vaccine protocol",
        },
      ],
      arrival_date: "2018-03-12",
      image_url: "",
      description:
        "Leo is a majestic male lion with a full mane. He's the dominant male in our lion pride and has fathered several cubs.",
    },
    {
      id: "a2",
      name: "Ellie",
      species: "Elephant",
      gender: "Female",
      age: 15,
      health_status: "Healthy",
      location: "Elephant Sanctuary",
      diet_requirements: "Herbivore diet: 150kg of vegetation daily, supplements",
      medical_history: [
        {
          date: "2023-11-05",
          type: "Foot Care",
          notes: "Regular foot maintenance performed",
          treatment: "Nail trimming and pad inspection",
        },
      ],
      arrival_date: "2015-06-18",
      image_url: "",
      description:
        "Ellie is a gentle African elephant who loves water activities. She's known for her intelligence and playful nature.",
    },
    {
      id: "a3",
      name: "Slither",
      species: "Python",
      gender: "Male",
      age: 12,
      health_status: "Concerning",
      location: "Reptile House",
      diet_requirements: "Carnivore: One medium rat every 2 weeks",
      medical_history: [
        {
          date: "2023-12-01",
          type: "Skin Condition",
          notes: "Showing signs of scale rot on lower body",
          treatment: "Topical antifungal treatment, habitat humidity adjustment",
        },
      ],
      arrival_date: "2016-09-30",
      image_url: "",
      description:
        "Slither is a Burmese python measuring over 12 feet long. He's currently receiving treatment for a minor skin condition.",
    },
    {
      id: "a4",
      name: "Hopper",
      species: "Kangaroo",
      gender: "Female",
      age: 6,
      health_status: "Healthy",
      location: "Australian Outback Exhibit",
      diet_requirements: "Herbivore: Grass, leaves, and specialized pellets",
      medical_history: [],
      arrival_date: "2020-02-15",
      image_url: "",
      description: "Hopper is an energetic red kangaroo who recently had a joey. She's very protective of her young.",
    },
    {
      id: "a5",
      name: "Bubbles",
      species: "Dolphin",
      gender: "Female",
      age: 10,
      health_status: "Healthy",
      location: "Marine Habitat",
      diet_requirements: "15kg of fish daily, vitamin supplements",
      medical_history: [],
      arrival_date: "2017-07-22",
      image_url: "",
      description:
        "Bubbles is a bottlenose dolphin who performs in our educational shows. She's highly intelligent and has mastered numerous tricks.",
    },
    {
      id: "a6",
      name: "Rocky",
      species: "Gorilla",
      gender: "Male",
      age: 12,
      health_status: "Concerning",
      location: "Primate House",
      diet_requirements: "Omnivore: Fruits, vegetables, nuts, and occasional insects",
      medical_history: [
        {
          date: "2023-11-20",
          type: "Dental Examination",
          notes: "Signs of tooth decay on lower molars",
          treatment: "Scheduled for dental procedure next week",
        },
      ],
      arrival_date: "2016-04-10",
      image_url: "",
      description:
        "Rocky is a silverback western lowland gorilla. He's the leader of our gorilla troop and is currently receiving dental care.",
    },
    {
      id: "a7",
      name: "Spots",
      species: "Giraffe",
      gender: "Female",
      age: 7,
      health_status: "Healthy",
      location: "African Plains",
      diet_requirements: "Herbivore: Acacia leaves, hay, and specialized pellets",
      medical_history: [],
      arrival_date: "2019-08-05",
      image_url: "",
      description:
        "Spots is a reticulated giraffe with distinctive pattern markings. She's one of our tallest residents at 16 feet.",
    },
    {
      id: "a8",
      name: "Frosty",
      species: "Polar Bear",
      gender: "Male",
      age: 9,
      health_status: "Critical",
      location: "Arctic Zone",
      diet_requirements: "Carnivore: Fish, seal meat, and specialized polar bear diet",
      medical_history: [
        {
          date: "2023-12-10",
          type: "Emergency Care",
          notes: "Showing signs of respiratory distress and lethargy",
          treatment: "IV antibiotics, oxygen therapy, 24-hour monitoring",
        },
        {
          date: "2023-12-11",
          type: "Follow-up",
          notes: "Condition stabilizing but still critical",
          treatment: "Continued antibiotics and supportive care",
        },
      ],
      arrival_date: "2018-11-30",
      image_url: "",
      description:
        "Frosty is currently under intensive veterinary care for a severe respiratory infection. His condition is being closely monitored.",
    },
  ]

  // Generate mock resources
  const resources: Resource[] = [
    {
      id: "r1",
      name: "Beef Quarters",
      category: "Food",
      quantity: 250,
      unit: "kg",
      status: "Available",
      last_restocked: "2023-12-01",
    },
    {
      id: "r2",
      name: "Hay Bales",
      category: "Food",
      quantity: 120,
      unit: "bales",
      status: "Available",
      last_restocked: "2023-11-15",
    },
    {
      id: "r3",
      name: "Fish Feed",
      category: "Food",
      quantity: 50,
      unit: "kg",
      status: "Low Stock",
      last_restocked: "2023-11-10",
    },
    {
      id: "r4",
      name: "Antibiotics",
      category: "Medical",
      quantity: 5,
      unit: "boxes",
      status: "Low Stock",
      last_restocked: "2023-10-20",
    },
    {
      id: "r5",
      name: "Bandages",
      category: "Medical",
      quantity: 30,
      unit: "packs",
      status: "Available",
      last_restocked: "2023-11-25",
    },
    {
      id: "r6",
      name: "Anesthetics",
      category: "Medical",
      quantity: 0,
      unit: "vials",
      status: "Out of Stock",
      last_restocked: "2023-09-15",
    },
    {
      id: "r7",
      name: "Cleaning Supplies",
      category: "Equipment",
      quantity: 45,
      unit: "units",
      status: "Available",
      last_restocked: "2023-11-30",
    },
    {
      id: "r8",
      name: "Maintenance Tools",
      category: "Equipment",
      quantity: 12,
      unit: "sets",
      status: "Available",
      last_restocked: "2023-10-05",
    },
    {
      id: "r9",
      name: "Safety Equipment",
      category: "Equipment",
      quantity: 8,
      unit: "sets",
      status: "Low Stock",
      last_restocked: "2023-11-01",
    },
  ]

  // Generate mock reports
  const reports: Report[] = [
    {
      id: "rpt1",
      title: "Monthly Health Assessment - December 2023",
      category: "Health",
      date: "2023-12-05",
      author: "Dr. Jane Smith",
      file_url: "",
    },
    {
      id: "rpt2",
      title: "Q4 Inventory Status Report",
      category: "Inventory",
      date: "2023-12-01",
      author: "Mark Johnson",
      file_url: "",
    },
    {
      id: "rpt3",
      title: "Annual Financial Summary 2023",
      category: "Financial",
      date: "2023-11-30",
      author: "Sarah Williams",
      file_url: "",
    },
    {
      id: "rpt4",
      title: "Polar Bear Health Crisis Report",
      category: "Incident",
      date: "2023-12-10",
      author: "Dr. Jane Smith",
      file_url: "",
    },
    {
      id: "rpt5",
      title: "New Animal Acquisition Proposal",
      category: "Financial",
      date: "2023-11-15",
      author: "Director Thomas",
      file_url: "",
    },
    {
      id: "rpt6",
      title: "Visitor Safety Incident - November 2023",
      category: "Incident",
      date: "2023-11-22",
      author: "Security Team",
      file_url: "",
    },
    {
      id: "rpt7",
      title: "Reptile House Maintenance Schedule",
      category: "Inventory",
      date: "2023-11-10",
      author: "Maintenance Dept",
      file_url: "",
    },
  ]

  return { animals, resources, reports }
}

